<#
    modules\reporting\Html.psm1

    GRC Engineering Platform
#>

<#
.SYNOPSIS
    HTML reporting module.

.DESCRIPTION
    Provides HTML report generation capabilities for
    compliance assessments, evidence reviews, scoring
    outputs, and executive reporting.

    Responsibilities:

    - Generate HTML reports
    - Create report sections
    - Render tables
    - Apply report styling
    - Export assessment results

.NOTES
    GRC Engineering Platform
    Version 1.0.0
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

#region Templates

$script:DefaultStyle = @"
<style>
body {
    font-family: Arial, Helvetica, sans-serif;
    color: #333333;
    margin: 40px;
}
h1 {
    color: #005A9E;
}
h2 {
    color: #0078D4;
    border-bottom: 1px solid #cccccc;
}
table {
    border-collapse: collapse;
    width: 100%;
}
th {
    background-color: #0078D4;
    color: white;
    padding: 8px;
}
td {
    border: 1px solid #dddddd;
    padding: 8px;
}
.status-success {
    color: green;
}
.status-failed {
    color: red;
}
.footer {
    margin-top: 40px;
    font-size: 12px;
    color: #666666;
}
</style>
"@

#endregion

#region Report Creation

function New-HtmlReport {
    <#
    .SYNOPSIS
        Creates a new HTML report.
    #>

    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Title,

        [string]$Author = "GRC Engineering Platform"
    )

    @"
<!DOCTYPE html>
<html>
<head>
<title>$Title</title>
$script:DefaultStyle
</head>
<body>
<h1>$Title</h1>
<p>Generated by: $Author</p>
<p>Generated: $(Get-Date -Format u)</p>
"@
}

function Complete-HtmlReport {
    <#
    .SYNOPSIS
        Completes an HTML document.
    #>

    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Content
    )

    $Content + @"
<div class="footer">
GRC Engineering Platform
</div>
</body>
</html>
"@
}

#endregion

#region Sections

function Add-HtmlSection {
    <#
    .SYNOPSIS
        Adds a report section.
    #>

    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Title,

        [Parameter(Mandatory)]
        [string]$Content
    )

    @"
<h2>$Title</h2>
<div>
$Content
</div>
"@
}

function Add-HtmlSummary {
    <#
    .SYNOPSIS
        Adds executive summary section.
    #>

    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [hashtable]$Summary
    )

    $rows = ""

    foreach ($item in $Summary.Keys) {

        $rows += @"
<tr>
<td>$item</td>
<td>$($Summary[$item])</td>
</tr>
"@
    }

    Add-HtmlTable `
        -Headers @(
        "Metric",
        "Value"
    ) `
        -Rows $rows
}

#endregion

#region Tables

function Add-HtmlTable {
    <#
    .SYNOPSIS
        Creates an HTML table.
    #>

    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string[]]$Headers,

        [Parameter(Mandatory)]
        [string]$Rows
    )

    $headerHtml = ""

    foreach ($header in $Headers) {

        $headerHtml += "<th>$header</th>"

    }

    @"
<table>
<thead>
<tr>
$headerHtml
</tr>
</thead>
<tbody>
$Rows
</tbody>
</table>
"@
}

function ConvertTo-HtmlTable {
    <#
    .SYNOPSIS
        Converts objects into HTML table.
    #>

    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [object[]]$Data
    )

    $Data |
    ConvertTo-Html `
        -Fragment
}

#endregion

#region Assessment Reports

function Export-GRCHtmlReport {
    <#
    .SYNOPSIS
        Exports HTML report to file.
    #>

    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Content,

        [Parameter(Mandatory)]
        [string]$Path
    )

    $Content |
    Out-File `
        -FilePath $Path `
        -Encoding UTF8

    Get-Item $Path
}

function New-ComplianceHtmlReport {
    <#
    .SYNOPSIS
        Creates compliance assessment report.
    #>

    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [object[]]$Controls,

        [Parameter(Mandatory)]
        [string]$Framework
    )

    $report =
    New-HtmlReport `
        -Title "$Framework Compliance Report"

    $table =
    ConvertTo-HtmlTable `
        -Data $Controls

    $report += Add-HtmlSection `
        -Title "Control Assessment" `
        -Content $table

    Complete-HtmlReport `
        -Content $report
}

#endregion

#region Health

function Test-HtmlReportingHealth {
    <#
    .SYNOPSIS
        Performs reporting module health check.
    #>

    [CmdletBinding()]
    param()

    [PSCustomObject]@{
        Status = "Healthy"
        Module = "Html"
        Engine = "PowerShell HTML Renderer"
    }
}

#endregion

Export-ModuleMember -Function @(
    "New-HtmlReport"
    "Complete-HtmlReport"
    "Add-HtmlSection"
    "Add-HtmlSummary"
    "Add-HtmlTable"
    "ConvertTo-HtmlTable"
    "Export-GRCHtmlReport"
    "New-ComplianceHtmlReport"
    "Test-HtmlReportingHealth"
)
